# Field Corner locations
# Make sure world coordinates are in meters if you used ros image pipeline to calibrate your camera, otherwise use the same units as your calibration method
world_coordinates: [[0.0, 0.0, 0.0],
                    [0.3894, 0.0, 0.0],
                    [0.3894, 0.2714, 0.0],
                    [0.0, 0.2714, 0.0]]
                    # [0.201, 0.0, 0.0],
                    # [0.201, 0.2714, 0.0]]

                    # white side, defensive corner
                    # white side, offensive corner
                    # grey side defensive corner
                    # grey side offensive corner
                    # white side midfield
                    # grey side midfield

image_coordinates: [[86.,  415.],
                    [554., 415.],
                    [554., 63.],
                    [86.,  63.]]
                    # [322., 410.],
                    # [322., 63.]]

# translation_est: [-0.145, -0.2, 0.310]
