error_threshold: 0.002 # testing threshold for homography calculation

# World coordinates are in meters.
world_coordinates: [[0.0,     0.0,     0.0], # automated side defensive corner
                    [0.3745,  0.0,     0.0], # automated side offensive corner
                    [0.3745,  0.2565,  0.0], # player side defensive corner
                    [0.0,     0.2565,  0.0], # player side offensive corner
                    [0.18725, 0.12825, 0.0], # center
                    [0.0,     0.12825, 0.0], # automated goal center
                    [0.3745,  0.12825, 0.0], # player goal center
                    [0.11,    0.07534, 0.0], # automated side defensive quardrant
                    [0.2645,  0.07534, 0.0], # automated side offensive quardrant
                    [0.2645,  0.18116, 0.0], # player side defensive quardrant
                    [0.11,    0.18116, 0.0]] # player side offensive quardrant

# Ensure each image coordinate has a decimal after it
image_coordinates: [[97.,  412.], # automated side defensive corner
                    [549., 406.], # automated side offensive corner
                    [549., 66.],  # player side defensive corner
                    [90.,  67.],  # player side offensive corner
                    [323., 240.], # center
                    [93.,  240.], # automated goal center
                    [547., 237.], # player goal center
                    [231., 309.], # automated side defensive quardrant
                    [416., 308.], # automated side offensive quardrant
                    [416., 166.], # player side defensive quardrant
                    [229., 169.]] # player side offensive quardrant
