
error_threshold: 0.002 # testing threshold for extrinsic properties calculation

# Make sure world coordinates are in meters if you used ros image pipeline to calibrate your camera, otherwise use the same units as your calibration method
world_coordinates: [[0.0,     0.0,     0.0],
                    [0.3745,  0.0,     0.0],
                    [0.3745,  0.2565,  0.0],
                    [0.0,     0.2565,  0.0],
                    [0.18725, 0.12825, 0.0],
                    [0.0,     0.12825, 0.0],
                    [0.3745,  0.12825, 0.0],
                    [0.11,    0.07534, 0.0],
                    [0.2645,  0.07534, 0.0],
                    [0.2645,  0.18116, 0.0],
                    [0.11,    0.18116, 0.0]]

                    # [0.0,     0.0,     0.010],
                    # [0.3745,  0.0,     0.010],
                    # [0.3745,  0.2565,  0.010],
                    # [0.0,     0.2565,  0.010],
                    # [0.18725, 0.12825, 0.010],
                    # [0.0,     0.12825, 0.010],
                    # [0.3745,  0.12825, 0.010],
                    # [0.11,    0.07534, 0.010],
                    # [0.2645,  0.07534, 0.010],
                    # [0.2645,  0.18116, 0.010],
                    # [0.11,    0.18116, 0.010],
                    #
                    # [0.0,     0.0,     0.020],
                    # [0.3745,  0.0,     0.020],
                    # [0.3745,  0.2565,  0.020],
                    # [0.0,     0.2565,  0.020],
                    # [0.18725, 0.12825, 0.020],
                    # [0.0,     0.12825, 0.020],
                    # [0.3745,  0.12825, 0.020],
                    # [0.11,    0.07534, 0.020],
                    # [0.2645,  0.07534, 0.020],
                    # [0.2645,  0.18116, 0.020],
                    # [0.11,    0.18116, 0.020]]

# Order of points in the list for a given height:
# white side defensive corner
# white side offensive corner
# grey side defensive corner
# grey side offensive corner
# center
# white goal center
# grey goal center
# white side defensive quardrant
# white side offensive quardrant
# grey side defensive quardrant
# grey side offensive quardrant

image_coordinates: [[97.,  412.],
                    [549., 406.],
                    [549., 66.],
                    [90.,  67.],
                    [323., 240.],
                    [93.,  240.],
                    [547., 237.],
                    [231., 309.],
                    [416., 308.],
                    [416., 166.],
                    [229., 169.]]

                    # [90.,  416.],
                    # [557., 409.],
                    # [558., 60.],
                    # [83.,  62.],
                    # [320., 239.],
                    # [89.,  241.],
                    # [556., 237.],
                    # [229., 312.],
                    # [417., 310.],
                    # [417., 167.],
                    # [226., 167.],
                    #
                    # [83.,  423.],
                    # [566., 417.],
                    # [564., 56.],
                    # [74.,  57.],
                    # [324., 239.],
                    # [79.,  242.],
                    # [564., 237.],
                    # [225., 314.],
                    # [421., 312.],
                    # [421., 164.],
                    # [223., 167.]]
